# Reference file : https://github.com/dell/csi-powerflex/tree/main/samples
#
- username: "admin"
  password: "Password123"
  systemID: "3592163a28ef7c0f"
  allSystemNames: "powerflex-01"
  endpoint: "10.60.156.96"
  skipCertificateValidation: true 
  mdm: "10.60.156.96"

